### ISSUE TITLE
Initial DB population

### ISSUE THREAD

**Issue by jerry40** [jlucid/qExplorer#9]
Hi!

I'm trying to fill the database initially and get some results, but I experience slow steps , especially "Saving table: addressLookup" one. Is there a way to make them faster? Run them less frequently perhaps? Or switch them off until all db is filled? I use 4 cpus.

2019.05.08D13:45:15.731140000 UTXO Count: 29659807
2019.05.08D13:45:15.768088000 Finished Processing Block
2019.05.08D13:45:18.375466000 Processing Block: 368013
2019.05.08D13:45:19.292360000 UTXO Count: 29678035
2019.05.08D13:45:19.305890000 Updating UTXO table
2019.05.08D13:45:21.619996000 Removed 3687 spent transactions.
2019.05.08D13:45:26.245539000 Recreating hash map : 0D00:00:04.625501000
2019.05.08D13:45:26.245586000 Saving table: blocks to partition 369
2019.05.08D13:45:26.249312000 Saving table: txInfo to partition 369
2019.05.08D13:45:26.404450000 Saving table: txInputs to partition 369
2019.05.08D13:45:26.535668000 Saving table: txOutputs to partition 369
2019.05.08D13:45:26.836910000 Saving table: txidLookup
2019.05.08D13:45:41.920815000 Saving table: addressLookup
2019.05.08D13:48:46.663789000 Creating checkpoint
2019.05.08D13:50:36.261311000 Finished creating checkpoint
2019.05.08D13:50:36.282472000 Finished Processing Block

Thanks!

**Comment by jlucid** [comment]
Yes that step is very slow.

Ultimately we need some alternative to store the addresses and txids more rapidly.

I created another branch called segregated refDB where a second process takes on the responsibility of generating the refDB at the same time as the qExplorer is running.

It basically looks at the mainDB and processes newly completed partitions.
I would recommend trying that.

In that case you can at least assign another core to the task.

To continue using the existing master branch you could increase the writeFreq to maybe 1000 but this does increase ram requirements.

**Comment by Tzadiko** [comment]
Hi Jerry40,

How much memory does your machine have? In order for you to both pass the IBD and perform long-running and complex queries, you'll need at least 40 GB of RAM. Are you on Master or the branch "Segregated-refDB-Construction"? The reference table does take a little while to run, that's why "Segregated-refDB-Construction" was created. Can you run:
df -h and show me the output?

Thanks,
Tomer

**Comment by jerry40** [comment]
Hi! Thanks for the quick response!

I have 16Gb , I am on the master branch

df -h 

```Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p2  980G  375G  606G  39% /
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G   17M  7.7G   1% /run
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
tmpfs           1.6G     0  1.6G   0% /run/user/1000```

**Comment by jerry40** [comment]
Yes I thought about playing with writeFreq etc, but I was afraid about the DB partitions, what if I somehow break already pulled data? I believe I can live with this speed but I think that this step will be slower with block numbers growth.
I like the idea with the another process though.. So all I need is to get more memory?

**Comment by jlucid** [comment]
Hi Jerry,

For storing the DB on disk, you will need about 0.5T.
This is with the compression which is enable by default.

Also, you will need about 64GB RAM because we are storing the
utxo table in memory. With that, you should be able to
have a writeFreq of 500, maybe even 1000, same as the chunkSize.

**Comment by jerry40** [comment]
Hi Jlucid, Tzadiko!

Thanks, so I'm learning how to increase my AWS instance memory and disk size. Hopefully, this will be easy. I'll return with questions in 1-2 days if you do not mind.
We can close this issue or continue discussing my experience here, as you wish.
Playing with kdb+ , q and qExplorer is so interesting, thanks for your work!

**Comment by jerry40** [comment]
Hi Jlucid, Tzadiko!
I upgraded the instance, so it has 64Gb now. Also I changed writeFreq to 1000, watching what happens next.

**Comment by jerry40** [comment]
The process is going well, I have 526000 blocks out of current 576000, so I'm closing this question, thanks!
